name: CI Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install clang lld meson ninja-build -y
          clang --version
          ld.lld --version

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install meson

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: pip install meson ninja

      - name: Set extra CMake flags
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            echo "EXTRA_FLAGS=-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXE_LINKER_FLAGS=\"-fuse-ld=lld\" -DCMAKE_SHARED_LINKER_FLAGS=\"-fuse-ld=lld\"" >> $GITHUB_ENV
          else
            echo "EXTRA_FLAGS=" >> $GITHUB_ENV
          fi

      - name: Configure CMake
        run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF ${{ env.EXTRA_FLAGS }} -B build -S .

      - name: Build zelph
        run: cmake --build build --config Release

      - name: Package build artifacts (Zip)
        shell: python
        run: |
          import shutil
          import os

          if os.name == 'nt':
              source_dir = "build/bin/Release"
          else:
              source_dir = "build/bin"

          output_filename = "zelph-${{ matrix.name }}"

          print(f"Zipping content of {source_dir} to {output_filename}.zip")

          shutil.make_archive(output_filename, 'zip', source_dir)

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zelph-${{ matrix.name }}
          path: zelph-${{ matrix.name }}.zip
