site_name: zelph - A Sophisticated Semantic Network System
theme:
  name: material
  features:
    - navigation.expand
    - content.code.annotate
nav:
  - Home: index.md
  - Quick Start Guide: quickstart.md
  - Binary Data Files: binaries.md
  - Use Case - Wikidata:
      - Overview: wikidata.md
      - Wikimedia Rapid Fund Report: grant-report.md
      - Disjointness Violations: disjointness-violations.md
      - Detected Split Order Violations:
          - Gene: split-order-classes/gene.md
          - Protein: split-order-classes/protein.md
          - All Other: split-order-classes/other.md
      - Constraint-based zelph rules: constraint-list.md
      - Detected constraint violations: constraints/!.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
extra_javascript:
  - https://unpkg.com/mermaid@11.4.1/dist/mermaid.min.js
extra:
  mermaid:
    version: 11.4.1
